platform :ios,'8.0'
use_frameworks!
target 'AutoLayoutTest' do
    pod 'AFNetworking', '~> 3.0'
    pod 'JSONModel'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'FMDB'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'ReactiveCocoa'
end